# Generated by Django 5.0.3 on 2024-04-08 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_group', models.CharField(max_length=2)),
                ('Bloodbankcity', models.CharField(max_length=10)),
                ('Blood_expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('National_ID', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14, message='National ID must be at least 14 characters long.')])),
                ('Name', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
